#!/bin/bash
# SPDX-License-Identifier: MIT
##############################################################################
# Copyright (c) 2016, 2017, 2018 The Linux Foundation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
##############################################################################

# This script checks out a git repo determined by repository_url and determines if
# it contains unsigned commits.


dco() {
    # Entry point for the dco command.
    subcommand=$1; shift

    case "$subcommand" in
        check )
            echo "Checking repository for unsigned commits..."
            check_dco "$@"
            exit 0
            ;;
        * )
            echo "Invalid command: $subcommand" 1>&2
            exit 1
            ;;
    esac
}

check_dco() {
    git log --no-merges --pretty="%H" --grep 'Signed-off-by' --invert-grep * | while read commit_hash; do
        echo "ERROR: Commit $commit_hash is not signed."
    done
}