#!/bin/bash
# SPDX-License-Identifier: EPL-1.0
##############################################################################
# Copyright (c) 2016, 2017 The Linux Foundation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
##############################################################################

main() {

echo "checking $gerriturl participation for group $group"

while read -r line; do

  group="$(echo "$line" | awk -F"," '{print $1}')"
  id="$(echo "$line" | awk -F"," '{print $2}')"
  fullname="$(echo "$line" | awk -F"," '{print $3}')"
  email="$(echo "$line" | awk -F"," '{print $NF}')"

  sixmonthsago=$(date -d "-6 month" +%Y-%m-%d)
  # Check if user can be found in gerrit in the last six months
  change_id="$(curl --silent "https://$gerriturl/changes/?q=""$id"+after:"$sixmonthsago""&n=1" | grep change_id)";

  if  [[ -z $change_id ]]; then

  # Check if user can be found in gerrit at all
  change_id="$(curl --silent "https://$gerriturl/changes/?q=$id&n=1" | grep change_id)";

    if  ! [[ -z $change_id ]]; then
      printf '%s\n' "$group \"$fullname\" has not used gerrit in _6_ months $email"
    else
      printf '%s\n' "$group \"$fullname\" has ______never______ used gerrit $email"
    fi
  
  else
    printf '%s\n' "$group \"$fullname\" is active"
  fi


done < <(lftools ldap csv --groups "$group")

}

usage() {
cat << EOF
This program searches gerrit by email for user participation
Email list can be built with 'ldap-lookup'
Program outputs users who have not used gerrit at all, or in the last 6 months
users from this list can be slated to have their access revoked.

If you encounter: "Cant contact LDAP server"

you will need to add:
TLS_CACERT /path/to/ca.crt in /etc/openldap/ldap.conf
ca.crt can be found on any collab system in /etc/ipa/ca.crt

Usage:
 $1  target gerrit url
 $2  target ldap group

ex: $0 gerrit.opnfv.org/gerrit opnfv-gerrit-releng-submitters 
EOF
}

if [[ $# -eq 0 ]] ; then usage "$@"
  exit 1
fi

gerriturl="$1"
group="$2"
main
