#!/bin/bash
# @License EPL-1.0 <http://spdx.org/licenses/EPL-1.0>
##############################################################################
# Copyright (c) 2017 The Linux Foundation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#   Thanh Ha - Initial implementation
##############################################################################

# lftools script acts as a main function for all the shell tools in the
# lf-releng-tools project.

SCRIPT_DIR=`dirname $(readlink -f ${BASH_SOURCE})`
echo $SCRIPT_DIR

print_usage() {
    echo "Usage:"
    echo "    lftools -h"
    echo "    lftools version        Run the version bumping script."
}

# Print the usage statement if the user provides no options
if [[ $# -eq 0 ]] ; then
    print_usage
    exit 0
fi

# Parse options for lftools command
while getopts ":h" opt; do
    case ${opt} in
        h )
            print_usage
            exit 0
            ;;
        \? )
            echo "Invalid Option: -$OPTARG" 1>&2
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))
subcommand=$1; shift

# Parse options for subcommands
case "$subcommand" in
    patch )
        echo "Now we run the patch command."
        exit 0
        ;;
    version )
        echo "Now we run the version command."
        source $SCRIPT_DIR/version
        version $@
        exit 0
        ;;
    * )
        echo "Invalid command: $subcommand" 1>&2
        exit 1
        ;;
esac
